# Set Seed for reproducability

In [74]:
import numpy as np
np.random.seed(42)

# Load dependencies

In [75]:
import keras
from keras.datasets import mnist
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import SGD

# Load Data

In [76]:
(x_train,y_train),(x_test,y_test) = mnist.load_data()

In [77]:
x_train.shape

(60000, 28, 28)

In [78]:
y_train.shape

(60000,)

In [79]:
y_train[0:99]

array([5, 0, 4, 1, 9, 2, 1, 3, 1, 4, 3, 5, 3, 6, 1, 7, 2, 8, 6, 9, 4, 0,
       9, 1, 1, 2, 4, 3, 2, 7, 3, 8, 6, 9, 0, 5, 6, 0, 7, 6, 1, 8, 7, 9,
       3, 9, 8, 5, 9, 3, 3, 0, 7, 4, 9, 8, 0, 9, 4, 1, 4, 4, 6, 0, 4, 5,
       6, 1, 0, 0, 1, 7, 1, 6, 3, 0, 2, 1, 1, 7, 9, 0, 2, 6, 7, 8, 3, 9,
       0, 4, 6, 7, 4, 6, 8, 0, 7, 8, 3], dtype=uint8)

In [80]:
x_test.shape

(10000, 28, 28)

In [81]:
x_test[0]

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  

In [82]:
y_test.shape

(10000,)

In [83]:
y_test[0]

7

# Preprocess Data

In [84]:
x_train= x_train.reshape(60000, 784).astype('float32')

In [85]:
x_test= x_test.reshape(10000, 784).astype('float32')

In [86]:
x_test[0]

array([  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   

In [87]:
x_train /= 255
x_test /= 255

In [88]:
x_test[0]

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.     

In [89]:
n_classes=10
y_train=keras.utils.to_categorical(y_train, n_classes)
y_test=keras.utils.to_categorical(y_test,n_classes)

In [90]:
y_test[0]

array([0., 0., 0., 0., 0., 0., 0., 1., 0., 0.], dtype=float32)

# Design neural network architecture

In [91]:
model=Sequential()
model.add(Dense(64, activation='sigmoid', input_shape=(784,)))
model.add(Dense(10, activation='softmax'))

model.summary()

In [92]:
(64*784)

50176

In [93]:
(64*784)+64

50240

In [94]:
(10*64)+10

650

# Configure Model

In [95]:
model.compile(loss="mean_squared_error",optimizer=SGD(lr=0.1), metrics=['accuracy'])

# Train

In [ ]:
model.fit(x_train,y_train,batch_size=128,epochs=400,verbose=1,validation_data=(x_test,y_test))

Train on 60000 samples, validate on 10000 samples
Epoch 1/400
60000/60000 [==============================] - 2s 27us/step - loss: 0.0106 - acc: 0.9336 - val_loss: 0.0105 - val_acc: 0.9331
Epoch 2/400
60000/60000 [==============================] - 2s 27us/step - loss: 0.0106 - acc: 0.9337 - val_loss: 0.0104 - val_acc: 0.9332
Epoch 3/400
60000/60000 [==============================] - 2s 27us/step - loss: 0.0106 - acc: 0.9338 - val_loss: 0.0104 - val_acc: 0.9336
Epoch 4/400
60000/60000 [==============================] - 2s 27us/step - loss: 0.0106 - acc: 0.9340 - val_loss: 0.0104 - val_acc: 0.9335
Epoch 5/400
60000/60000 [==============================] - 2s 26us/step - loss: 0.0106 - acc: 0.9343 - val_loss: 0.0104 - val_acc: 0.9336
Epoch 6/400
60000/60000 [==============================] - 2s 26us/step - loss: 0.0105 - acc: 0.9343 - val_loss: 0.0104 - val_acc: 0.9339
Epoch 7/400
60000/60000 [==============================] - 2s 26us/step - loss: 0.0105 - acc: 0.9344 - val_loss: 0.0104 - 

60000/60000 [==============================] - 2s 26us/step - loss: 0.0097 - acc: 0.9402 - val_loss: 0.0097 - val_acc: 0.9371
Epoch 60/400
60000/60000 [==============================] - 2s 26us/step - loss: 0.0097 - acc: 0.9404 - val_loss: 0.0097 - val_acc: 0.9377
Epoch 61/400
60000/60000 [==============================] - 2s 26us/step - loss: 0.0097 - acc: 0.9404 - val_loss: 0.0096 - val_acc: 0.9380
Epoch 62/400
60000/60000 [==============================] - 2s 26us/step - loss: 0.0097 - acc: 0.9406 - val_loss: 0.0096 - val_acc: 0.9380
Epoch 63/400
60000/60000 [==============================] - 2s 26us/step - loss: 0.0096 - acc: 0.9407 - val_loss: 0.0096 - val_acc: 0.9379
Epoch 64/400
60000/60000 [==============================] - 2s 26us/step - loss: 0.0096 - acc: 0.9407 - val_loss: 0.0096 - val_acc: 0.9378
Epoch 65/400
60000/60000 [==============================] - 2s 26us/step - loss: 0.0096 - acc: 0.9409 - val_loss: 0.0096 - val_acc: 0.9382
Epoch 66/400
60000/60000 [==============

Epoch 118/400
60000/60000 [==============================] - 2s 26us/step - loss: 0.0089 - acc: 0.9451 - val_loss: 0.0090 - val_acc: 0.9427
Epoch 119/400
60000/60000 [==============================] - 2s 26us/step - loss: 0.0089 - acc: 0.9452 - val_loss: 0.0090 - val_acc: 0.9424
Epoch 120/400
60000/60000 [==============================] - 2s 26us/step - loss: 0.0089 - acc: 0.9453 - val_loss: 0.0090 - val_acc: 0.9425
Epoch 121/400
60000/60000 [==============================] - 2s 26us/step - loss: 0.0089 - acc: 0.9453 - val_loss: 0.0090 - val_acc: 0.9427
Epoch 122/400
60000/60000 [==============================] - 2s 26us/step - loss: 0.0089 - acc: 0.9454 - val_loss: 0.0090 - val_acc: 0.9426
Epoch 123/400
60000/60000 [==============================] - 2s 26us/step - loss: 0.0089 - acc: 0.9456 - val_loss: 0.0090 - val_acc: 0.9425
Epoch 124/400
60000/60000 [==============================] - 2s 26us/step - loss: 0.0089 - acc: 0.9454 - val_loss: 0.0090 - val_acc: 0.9426
Epoch 125/400
60000/

60000/60000 [==============================] - 2s 26us/step - loss: 0.0083 - acc: 0.9489 - val_loss: 0.0085 - val_acc: 0.9462
Epoch 177/400
60000/60000 [==============================] - 2s 26us/step - loss: 0.0083 - acc: 0.9489 - val_loss: 0.0085 - val_acc: 0.9461
Epoch 178/400
60000/60000 [==============================] - 2s 26us/step - loss: 0.0083 - acc: 0.9489 - val_loss: 0.0085 - val_acc: 0.9462
Epoch 179/400
60000/60000 [==============================] - 2s 26us/step - loss: 0.0083 - acc: 0.9490 - val_loss: 0.0085 - val_acc: 0.9464
Epoch 180/400
60000/60000 [==============================] - 2s 26us/step - loss: 0.0083 - acc: 0.9491 - val_loss: 0.0085 - val_acc: 0.9465
Epoch 181/400
60000/60000 [==============================] - 2s 26us/step - loss: 0.0083 - acc: 0.9491 - val_loss: 0.0085 - val_acc: 0.9466
Epoch 182/400
60000/60000 [==============================] - 2s 26us/step - loss: 0.0083 - acc: 0.9493 - val_loss: 0.0084 - val_acc: 0.9464
Epoch 183/400
60000/60000 [=======

60000/60000 [==============================] - 2s 28us/step - loss: 0.0078 - acc: 0.9521 - val_loss: 0.0080 - val_acc: 0.9487
Epoch 235/400
60000/60000 [==============================] - 2s 26us/step - loss: 0.0078 - acc: 0.9523 - val_loss: 0.0080 - val_acc: 0.9487
Epoch 236/400
60000/60000 [==============================] - 2s 26us/step - loss: 0.0078 - acc: 0.9524 - val_loss: 0.0080 - val_acc: 0.9485
Epoch 237/400
60000/60000 [==============================] - 2s 26us/step - loss: 0.0077 - acc: 0.9523 - val_loss: 0.0080 - val_acc: 0.9487
Epoch 238/400
60000/60000 [==============================] - 2s 27us/step - loss: 0.0077 - acc: 0.9524 - val_loss: 0.0080 - val_acc: 0.9490
Epoch 239/400
60000/60000 [==============================] - 2s 27us/step - loss: 0.0077 - acc: 0.9524 - val_loss: 0.0080 - val_acc: 0.9487
Epoch 240/400
60000/60000 [==============================] - 2s 28us/step - loss: 0.0077 - acc: 0.9526 - val_loss: 0.0080 - val_acc: 0.9490
Epoch 241/400
60000/60000 [=======

60000/60000 [==============================] - 2s 26us/step - loss: 0.0073 - acc: 0.9554 - val_loss: 0.0076 - val_acc: 0.9511
Epoch 293/400
60000/60000 [==============================] - 2s 29us/step - loss: 0.0073 - acc: 0.9554 - val_loss: 0.0076 - val_acc: 0.9513
Epoch 294/400
60000/60000 [==============================] - 2s 26us/step - loss: 0.0073 - acc: 0.9556 - val_loss: 0.0076 - val_acc: 0.9512
Epoch 295/400
60000/60000 [==============================] - 2s 28us/step - loss: 0.0073 - acc: 0.9554 - val_loss: 0.0076 - val_acc: 0.9514
Epoch 296/400
60000/60000 [==============================] - 2s 27us/step - loss: 0.0073 - acc: 0.9556 - val_loss: 0.0076 - val_acc: 0.9511
Epoch 297/400
60000/60000 [==============================] - 2s 27us/step - loss: 0.0073 - acc: 0.9557 - val_loss: 0.0076 - val_acc: 0.9510
Epoch 298/400
60000/60000 [==============================] - 2s 29us/step - loss: 0.0073 - acc: 0.9556 - val_loss: 0.0076 - val_acc: 0.9514
Epoch 299/400
60000/60000 [=======

In [98]:
model_evaluate(x_test,y_test)

NameError: name 'model_evaluate' is not defined